import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/database/app_database.dart' as db;
import 'core/routing/app_router.dart';
import 'core/theme/app_theme.dart';
import 'features/alerts/alert_evaluation_service.dart';
import 'features/auth/auth_state.dart';
import 'features/auth/presentation/auth_gate.dart';
import 'shared/services/notification_service.dart';
import 'shared/services/sync_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Firebase config comes from platform files (GoogleService-Info.plist /
  // google-services.json) generated by `flutterfire configure` — see
  // README.md "Firebase setup steps". Nothing secret is hardcoded here
  // (hard constraint #8).
  await Firebase.initializeApp();

  runApp(const ProviderScope(child: FamilyHealthApp()));
}

class FamilyHealthApp extends ConsumerStatefulWidget {
  const FamilyHealthApp({super.key});

  @override
  ConsumerState<FamilyHealthApp> createState() => _FamilyHealthAppState();
}

class _FamilyHealthAppState extends ConsumerState<FamilyHealthApp> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) => _bootstrap());
  }

  Future<void> _bootstrap() async {
    await ref.read(notificationServiceProvider).initialize();

    // Kick an initial sync + alert evaluation once signed in. A real
    // background schedule (WorkManager/BGTaskScheduler) is a Phase 2 item —
    // see README.md "Known limitations" — Phase 1 syncs on app foreground
    // only, which is consistent with ARCHITECTURE.md §10's Decision to ship
    // on-device evaluation only while the app has synced recently.
    ref.listenManual(authStateChangesProvider, (previous, next) {
      final user = next.value;
      if (user == null) return;
      final userId = ref.read(currentUserIdProvider);
      if (userId == null) return;
      Future(() async {
        // Keep the local `users` row (DATABASE_SCHEMA.md §users) in sync
        // with Firebase's identity on every sign-in. Nothing reads this
        // table yet in Phase 1's UI (screens scope by Firebase uid
        // directly), but it's the local record Settings/family-admin
        // features (§26) will need, so it shouldn't sit permanently empty.
        // `role` defaults to 'member' — there's no admin-designation UI in
        // Phase 1, so every signed-in family member starts as a member.
        await ref.read(db.appDatabaseProvider).usersDao.upsertUser(db.UsersCompanion.insert(
              id: userId,
              email: user.email ?? '',
              displayName: user.displayName ?? user.email ?? 'Family member',
              role: 'member',
              createdAt: DateTime.now(),
            ));

        await ref.read(syncServiceProvider).syncAll(userId);
        await ref.read(alertEvaluationServiceProvider).evaluateAll(userId);
      });
    }, fireImmediately: true);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Family Health',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.system,
      routerConfig: appRouter,
      builder: (context, child) => AuthGate(child: child ?? const SizedBox.shrink()),
    );
  }
}
